package common.enums;

public enum Command {

    LOGIN,
    LOGOUT,
    FIND_CLIENT,
    CREATE_CLIENT,
    FIND_SPECIALIST,
    FIND_FULL_DATES,
    FIND_AVAILABLE_HOURS,
    CREATE_APPOINTMENT,
    FIND_APPOINTMENTS,
    CANCEL_APPOINTMENT,
    FIND_REFERENCE_BY_SID_CID_DATE, 
    FIND_REFERENCE_BY_REFNUM,
    REMOVE_CLIENT,
    RETURN_CLIENT;
    
}
